services:
  - type: web
    name: icon-invoice
    env: docker
    plan: free
    buildCommands: 
      - apt-get update && apt-get install -y libpango-1.0-0 libcairo2 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python manage.py collectstatic --noinput
      - python manage.py migrate
    startCommand: gunicorn icon_invoice.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: icon_invoice.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com 
      - key: DATABASE_URL
        sync: false 
