# Generated by Django 5.2.6 on 2025-09-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_invoiceaudit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
