# Generated by Django 5.2.6 on 2025-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='custom_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
