# Generated by Django 5.2.6 on 2025-10-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_party_address_line1_alter_party_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic',
        ),
    ]
