name: Daily Postgres Backup

on:
  schedule:
    # Run daily at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch: {}  # Allows manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PostgreSQL client and DNS tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget ca-certificates dnsutils
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17
          echo "/usr/lib/postgresql/17/bin" >> $GITHUB_PATH

      - name: Resolve Host and Create DB Dump
        env:
          # Hum saare secrets yahan la rahe hain
          PGHOST_NAME: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGSSLMODE: require
        run: |
          set -e
          
          # Pehle host ka IPv4 address dhoondho
          IPV4_HOST=$(dig +short A $PGHOST_NAME | head -n1)
          echo "Resolved IPv4 address for $PGHOST_NAME is: $IPV4_HOST"
          
          # Check karo ki IP mila ya nahi
          if [ -z "$IPV4_HOST" ]; then
            echo "::error::Could not resolve hostname to an IPv4 address."
            exit 1
          fi
          
          # Ab backup banao
          timestamp=$(date -u +'%Y%m%dT%H%M%SZ')
          filename="db-backup-${timestamp}.dump"
          echo "Dumping database to $filename from host $IPV4_HOST..."
          
          # -h flag ka istemal karke IP address pass karo
          pg_dump -Fc -h "$IPV4_HOST" -f "$filename"
          
          ls -lh "$filename"

      - name: Upload backup as Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backup-${{ github.run_id }}-${{ github.run_number }}
          path: db-backup-*.dump
          retention-days: 90
